name: Build And Deploy

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install zola
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install zola --edge
      - name: zola build
        run: zola build
      - name: Set CNAME
        run: echo "ksquad.jp" > ./public/CNAME
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
